Repository mattermost/mattermost-plugin-nps, pull requests merged in 2019-07, with the labels that each got.

#43 Enable coverage report
  .circleci/config.yml
  Makefile
  README.md
  server/.gitignore
Labels: 2: Dev Review

#45 MM-16611: leverage relative action URLs
  plugin.json
  server/api_test.go
  server/survey.go
  server/survey_test.go
Labels: 2: Dev Review

#44 MM-16609- Updating bg for nps rating
  webapp/src/components/survey_post/score.jsx
  webapp/src/components/survey_post/survey_post.jsx
Labels: 1: PM Review

#48 MM-16285 Rename NPS surveys to user satisfaction surveys
  README.md
  plugin.json
  server/activate.go
  server/lock.go
  server/segment.go
  server/survey.go
  server/survey_templates.go
  webapp/package.json
Labels: 3: Reviews Complete
