Repository mattermost/mattermost-plugin-nps, pull requests merged in 2019-03, with the labels that each got.

#8 Fix AnsweredAt not being set
  server/api.go
  server/survey.go
  server/survey_test.go
Labels: 3: Reviews Complete

#9 MM-14691 Add channel header message for SurveyBot
  server/hooks.go
Labels: 2: Dev Review

#10 MM-14501 Update help text links to point to redirects
  plugin.json
Labels: 3: Reviews Complete

#11 Update answered survey posts based on UX feedback
  server/api.go
  server/survey.go
Labels: 3: Reviews Complete

#12 MM-14340 Send written feedback to Segment
  server/hooks.go
  server/utils.go
Labels: 3: Reviews Complete

#7 Various bug fixes
  server/api.go
  server/hooks.go
  server/survey.go
  server/survey_templates.go
  server/utils.go
Labels: 3: Reviews Complete

#13 Use min_server_version instead of selfwritten solution
  plugin.json
  server/activate.go
Labels: Awaiting PR

#3 Add profile image for bot
  assets/generate.go
  assets/icon-happy-bot-square@1x.png
  assets/icon-happy-bot-square@2x.png
  server/activate.go
  server/profile_image.go
Labels: 3: Reviews Complete

#5 Add .editorconfig
  .editorconfig
Labels: 3: Reviews Complete

#4 MM-14341 Add confirmation modal when sending written feedback
  server/api.go
  webapp/package-lock.json
  webapp/package.json
  webapp/src/action_types.js
  webapp/src/actions.js
  webapp/src/client.js
  webapp/src/components/confirm_feedback_modal/confirm_feedback_modal.jsx
  webapp/src/components/confirm_feedback_modal/index.js
  webapp/src/components/root.jsx
  webapp/src/hooks.js
  webapp/src/index.js
  webapp/src/reducers.js
  webapp/src/selectors.js
  webapp/webpack.config.js
Labels: 3: Reviews Complete

#16 fix context in circleci
  .circleci/config.yml
Labels: 3: Reviews Complete

#14 Use min_server_version instead of selfwritten solution
  plugin.json
  server/activate.go
Labels: 3: Reviews Complete

#6 if diagnostics are disabled fail to start the plugin
  server/activate.go
Labels: 3: Reviews Complete

#18 Attempt to use existing Surveybot account if it already exists
  server/activate.go
Labels: 2: Dev Review

#17 MM-14553 Add nps-test command and refactor for test build
  server/activate.go
  server/survey.go
  server/test_commands.go
Labels: 3: Reviews Complete

#23 Change server side to be indipented of plugin ID
  server/survey.go
  server/survey_templates.go
Labels: 2: Dev Review

#20 Use plugin ID from manifest for API calls
  webapp/src/client.js
Labels: 3: Reviews Complete

#22 Properly set Surveybot's description
  server/activate.go
  server/hooks.go
  server/plugin.go
Labels: 3: Reviews Complete

#15 Load profile image for bot from file
  Makefile
  assets/generate.go
  assets/icon-happy-bot-square@2x.png
  server/Gopkg.lock
  server/Gopkg.toml
  server/activate.go
  server/profile_image.go
Labels: 3: Reviews Complete

#24 Minor fixes and tweaks
  plugin.json
  server/activate.go
  server/hooks.go
  server/survey.go
  server/survey_templates.go
  server/utils.go
Labels: 3: Reviews Complete
