Repository mattermost/mattermost-plugin-nps, pull requests merged in 2020-09, with the labels that each got.

#75 MM-25887 Ability to disable NPS surveys on a user level
  server/api.go
  server/api_test.go
  server/survey.go
  server/survey_test.go
  server/telemetry.go
  webapp/src/components/survey_post/survey_post.jsx
Labels: 2: Dev Review, 3: QA Review

#62 MM-23703 Use thread for User Satisfaction Surveybot messages
  server/hooks.go
  server/hooks_test.go
Labels: 3: QA Review

#74 Close client after deactivation
  server/activate.go
Labels: 4: Reviews Complete

#77 MM-28520-Update NPS plugin version
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 3: QA Review

#78 Add release_notes_url
  plugin.json
  server/manifest.go
  webapp/src/manifest.js
Labels: 4: Reviews Complete
