Repository mattermost/mattermost-plugin-nps, pull requests merged in 2022-10, with the labels that each got.

#91 Fix linter errors
  .golangci.yml
Labels: 4: Reviews Complete

#92 [MM-46440]: Change Mattermost logo from grey to black
  server/survey_templates.go
Labels: 2: Dev Review, 1: UX Review, 3: QA Review, Setup Cloud Test Server

#94 [MM-46818] Ask for email on confirmation popin
  server/hooks.go
  server/telemetry.go
  webapp/src/components/confirm_feedback_modal/confirm_feedback_modal.jsx
  webapp/src/hooks.js
Labels: 1: UX Review

#96 Automate backend manifest read
  server/manifest.go
  server/survey.go
  server/telemetry.go
Labels: 4: Reviews Complete

#97 Bump version to 1.3.0
  plugin.json
Labels: 2: Dev Review
